### ISSUE TITLE
Site Mapping exercise

### ISSUE THREAD

**Issue by davidwtalley** [ld4pe/ld4pe-general#10]
Notes from the last monthly call suggest that a site mapping exercise is called for, and I heartily agree. I started a site map document a while back that may be a starting point to review and revise. I will look for a way to attach the PDF, but here's a screen shot. @stuartasutton how would you like to proceed? Set up a call specific to this issue? If yes, who would be the participants?

![image](https://cloud.githubusercontent.com/assets/10350595/9429265/2631c38a-497f-11e5-9e25-c963364b8462.png)

**Comment by stuartasutton** [comment]
@davidwtalley, I think a call would be in order so we can go over the Draft 0.1 map. Many of us are going into DC-2015 in Brazil this week and otherwise occupied until Sept. 4. 

I'd also like to put on the agenda for that call some matters from the the "LD4PE Wireframes, version 0.2".

**Comment by davidwtalley** [comment]
@stuartasutton when is a good time to schedule this meeting?

**Comment by stuartasutton** [comment]
How about this coming Wednesday, 7:30am
?

**Comment by mikecrandall** [comment]
I’m back in town for at least a short time and can join at this time if it works for David..

Thanks,
Mike

**Comment by stuartasutton** [comment]
@davidwtalley, is this Wednesday at  7:30am PDT OK with you for the site map and hopefully some of the wireframes (#22)? @mikecrandall can join us. If so, I'll set up WebEx and attached the two documents.

**Comment by davidwtalley** [comment]
Sorry - yes,  that's doable. 
Ans we might be thinking of another session soon with Abi & Joseph to talk over the draft competency browse wireframes. 
- David 
On Sep 28, 2015 4:46 PM, Stuart Sutton <notifications@github.com> wrote:@davidwtalley, is this Wednesday at  7:30am PDT OK with you for the site map and hopefully some of the wireframes (#22)? @mikecrandall can join us. If so, I'll set up WebEx and attached the two documents.
