### ISSUE TITLE
Resource description refresh on WP after edit in triplestore

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/ld4pe-general#12]
@abievans, @davidwtalley & @josephrchapman, I edited and saved changes to one of the "0 to 60" records on WordPress [1] last week using the angularJS editor. If you open the triplestore record in the editor using the resource URI [2] you can see that the record in the triplestore and the WP record are different. It does not appear that the resource descriptions in the WP are being refreshed after edits.

[1] http://explore.dublincore.net/learning_resource/0-to-60-on-sparql-queries-in-50-minutes/
[2] http://www.screencast.com/t/4pzAoMjyeJ

**Comment by abievans** [comment]
I forced a refresh of the resources and it seems to have updated. I’ll need to do some investigating to see why it wasn’t updated in the daily refresh. Could you send me an email if you make any other edits to triplestore descriptions? That will help me to debug the issue.

**Comment by stuartasutton** [comment]
Yes, I should have thought to do that, Abi, so you know where to look.

Stuart

**Comment by stuartasutton** [comment]
Abi, I just made another change to the same record (
http://www.screencast.com/t/4pzAoMjyeJ) to add another competency. A
successfully updated record should have two competencies instead of the
current one.

Stuart

**Comment by abievans** [comment]
Thanks, Stuart. I’ll check the record in WP tomorrow (the update runs once every 24 hours).

**Comment by stuartasutton** [comment]
Super!
