### ISSUE TITLE
Search box obscured by About menu dropdown

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/ld4pe-general#14]
@davidwtalley, when you click the right-hand search spyglass icon to open the search text box and then slide your mouse from spyglass to text entry (app. direction of 8'00 o'clock), you trigger the "About" dropdown menu that then significantly obscures the entry box.

![ld4pe-search](https://cloud.githubusercontent.com/assets/2939046/10016617/2ab95074-60dd-11e5-8e3a-e0d95c67370e.png)

**Comment by davidwtalley** [comment]
I added some left padding to the search control, so the menu item does not get hovered while moving the mouse to the search input box. This solution has a significant risk related to the count and wording of top-level menu items. To start to address this, I changed the label News & Announcements to News & Events. A real solution is pending the site-mapping exercise mentioned in issue #10.

Anything else needed here for now @stuartasutton?

**Comment by stuartasutton** [comment]
Let's close this.
