### ISSUE TITLE
LR browse wireframe review

### ISSUE THREAD

**Issue by davidwtalley** [ld4pe/ld4pe-general#22]
@stuartasutton when is a good time for us to review the draft wireframes (PDF attached to this ticket) for the learning resource browse interface(s)?
[ld4pe_v0.3.pdf](https://github.com/ld4pe/ld4pe-general/files/2974/ld4pe_v0.3.pdf)

**Comment by abievans** [comment]
I've added a private page with a working version of the competency list shortcode that implements some of the functionality from the wireframes - the two column browse interface and the collapsed index. Both features can be configured from the shortcode. You have to be logged in to Wordpress to see the page: http://explore.dublincore.net/browse-ci-test/

**Comment by davidwtalley** [comment]
I saw that. It's looking good! 
Had some trouble with the expand/collapse on my tablet, but I'll try it on the PC. 
On Oct 20, 2015 8:01 AM, abievans <notifications@github.com> wrote:I've added a private page with a working version of the competency list shortcode that implements some of the functionality from the wireframes - the two column browse interface and the collapsed index. Both features can be configured from the shortcode. You have to be logged in to Wordpress to see the page: http://explore.dublincore.net/browse-ci-test/
