### ISSUE TITLE
Link highlighting

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/ld4pe-general#30]
@davidwtalley & @abievans, on the last sprint call we discussed the underlining of links and the UX issues. The major underlining overload is with the CI which is end-to-end links [1]. Would it be possible to declare more than one link class [2] and for the CI only, eliminate __any special treatment__ except for hover? 

I am also wondering whether switching the base link treatment to solid underline and use the dashed for hover would be better.

Just thinking out loud.

[1] http://explore.dublincore.net/browse-ci-test/
[2] http://www.dreamweaverclub.com/css-multiple-link-styles.php

**Comment by davidwtalley** [comment]
Yes, both are possible. Another possibility might be to append a symbol before or after a link in-line [1] and use the solid underscore for the hover state and maybe also visited. This would be visually cleaner, I am sure, and still meet accessibility guidelines for calling out links via something other than colors.
  
 I will give both of these a look next chance I get.
  
 - David
  
 [1] http://tex.stackexchange.com/questions/22536/what-symbol-can-be-used-in-front-of-a-url
  
  

----------------------------------------

**Comment by davidwtalley** [comment]
This may have been a better link:
  
 http://webaim.org/techniques/hypertext/hypertext_links#new_window
  

----------------------------------------

**Comment by stuartasutton** [comment]
Appending symbol might work well...
