### ISSUE TITLE
FAQ stopped working

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/ld4pe-general#31]
@davidwtalley, the FAQ functionality was working quite well on explore. I started working today on an FAQ for dublincore and it did not work--i.e., neither the FAQs or the FAQ categories show up. When I double checked with the explore site, same result.

**Comment by davidwtalley** [comment]
A revision 2 weeks ago replaced a paragraph of text with a nonbreaking space, but the bigger issue is the lack of posts in the FAQ custom post type. They're in the dashboard but not on the page. 

I'm not familiar with the FAQ page template but I suspect it's an Avada thing. Might be similar to the nonworking slider bar, whjch I think started with the v 4.3.1 upgrade. I'll get tat support account created and look for known issues. 

- David

**Comment by stuartasutton** [comment]
I spent some time with the FAQ functionality, read the directions in Avada help. It is pretty straight forward. The individual entires never end up as actual text saved on the FAQ page. You create the page and select the template type of FAQ and put what ever lead-n text you want. After saving, you use the FAQ link in the admin navigation to access the actual FAQs, create new ones, and create FAQ categories. It was working exactly as all of the documentation said it would. 

Then it didn't :-(
