### ISSUE TITLE
WordPress settings too low

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/ld4pe-general#38]
I just looked at the WP settings at http://explore.dublincore.net/wp-admin/admin.php?page=avada-system-status and we still have some settings that are below recommended values. Is there a reason we don't up these limits:

--WP Memory Limit @ 64mb / minimum recommended 128mb
--PHP Max Input Vars @ 1000 / recommended 1760

**Comment by josephrchapman** [comment]
I made these updates.  Can you please confirm and close if fixed?

**Comment by stuartasutton** [comment]
Thanks, Joseph. The max input vars is now at 1760. But the memory limit in wp-config.php remains at 64.

**Comment by josephrchapman** [comment]
I updated it in a different spot.  Please try again and let me know

**Comment by stuartasutton** [comment]
Bingo. Issue closed
