### ISSUE TITLE
Adding calendar for upcoming events

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/ld4pe-general#7]
It might be useful for us to add a calendar feature [1] to the website for announcing upcoming events, e.g., where members of the team will be presenting etc. and other events of interest.

[1[ https://wordpress.org/plugins/tags/calendar-widget

**Comment by davidwtalley** [comment]
Spider Event Calendar is widely used with a good reputation and solid features. It's in place on the site now, with an event added at [1]. Documentation is at [2]. The one event I added is DC 2015 on Sept. 1 to show how the thing wants to work out of the box. Next steps:

1. Decide where the calendar lives on the site. It's not showing as a submenu item under News & Announcements (the home that made the most sense to me), but we can insert a static call-out to it on the front page, and we can insert a smaller widget version in the left or right rail on one or more pages. This determination is probably part of the separate wider site mapping task.

2. Determine whether the pro version is worth the cost. It's not much, but it look like a recurring license fee. The selection of calendar themes we'd gain is probably a good idea, and/or we can try to update its stylesheet manually. [3]

[1] http://explore.dublincore.net/news-announcements/explore-events/
[2] https://web-dorado.com/wordpress-spider-calendar/publishing-calendar.html
[3] https://web-dorado.com/products/wordpress-calendar.html

**Comment by stuartasutton** [comment]
Dave, having the calendar as a submenu under News & Announcements seems appropriate to me. During the course of the LR4PE project, maybe the calendar on the homepage might not be a bad idea. It could be used for calendaring meetings where we'll be attending etc. We could at least try it. I'll look at the pro and come to some conclusion about whether to go that route.

**Comment by davidwtalley** [comment]
I added the calendar to the standard page template in the right rail, so it will show up on all pages using that template. Please see what you think @stuartasutton. I also added a couple events, one each in Oct and Nov, so we can see how those listings will appear.

Clearly some CSS updates are needed to get the thing looking better, both in the right rail and on the Explore Events landing page. I don't want to undertake those until we get more clarity on where we want to place calendars on the site.
