### ISSUE TITLE
Version 4.3 upgrade

### ISSUE THREAD

**Issue by davidwtalley** [ld4pe/ld4pe-general#9]
It looks like we won't be able to rely on the WordPress automated upgrade function, because it prompts for normal FTP credentials, and we have two-factor authentication in place. (Or @josephrchapman is there some way to let the application past that obstacle to complete the upgrade?) As far as I know now, we'll have to manually upgrade.

Before our first version upgrade under multi-site, I want to be sure to back up both files and database. I have copied down the files, but I will ask Joseph to take a backup of the db. Then please assign back to me, and I will run the upgrade.

**Comment by josephrchapman** [comment]
Was this working before?  I think it was but want to double check.  Last time I think I by-passed that by doing:

1. Open /wp-config.php
2. define('FS_METHOD','direct');
3. Change ownership of all WP files in that directory to the webserver user so that it can freely manage those files.

@davidwtalley if that sounds right I can make that change.  Again, I'm thinking this was done last time and just needs to be done again since we moved everything.

**Comment by davidwtalley** [comment]
It was working before the migration to multi-site, yes.  And that migration did replace the /wp/wp-config.php file. I support making the changes you propose to see if we can get the auto-upgrade function. I have all the files backed up, in case the my be needed. 
On Aug 23, 2015 5:07 PM, Joseph Chapman <notifications@github.com> wrote:Was this working before?  I think it was but want to double check.  Last time I think I by-passed that by doing:

Open /wp-config.phpdefine('FS_METHOD','direct');Change ownership of all WP files in that directory to the webserver user so that it can freely manage those files.

@davidwtalley if that sounds right I can make that change.  Again, I'm thinking this was done last time and just needs to be done again since we moved everything.

**Comment by josephrchapman** [comment]
The db has been backed up, wp-config updated and all files should be under the apache/www user (this of course may impact what you can/can't update directly on the server again...).

**Comment by davidwtalley** [comment]
@josephrchapman to the rescue! Upgrade processes (both wp 4.3 and network upgrade) went off without a hitch, as far as I can tell. Things look good to me.
